### ISSUE TITLE
Hit tracker won't update

### ISSUE THREAD

**Issue by Amelie121** [brandonhellman/mturk-suite#150]
My hit tracker won't sync today or last 45 days. The overview columns are blank and it does nothing when I try to sync. 
these are the errors in the console:
Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
    at Promise (chrome-extension://iglbakfobmoijpbigmlfklckogbefnlf/hit_tracker/hit_tracker.js:39:38)
    at new Promise (<anonymous>)
    at todaysOverviewData (chrome-extension://iglbakfobmoijpbigmlfklckogbefnlf/hit_tracker/hit_tracker.js:38:10)
    at todaysOverview (chrome-extension://iglbakfobmoijpbigmlfklckogbefnlf/hit_tracker/hit_tracker.js:18:22)
    at initialize (chrome-extension://iglbakfobmoijpbigmlfklckogbefnlf/hit_tracker/hit_tracker.js:5:3)
hit_tracker.js:170 Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
    at Promise (chrome-extension://iglbakfobmoijpbigmlfklckogbefnlf/hit_tracker/hit_tracker.js:170:38)
    at new Promise (<anonymous>)
    at trackerOverviewData (chrome-extension://iglbakfobmoijpbigmlfklckogbefnlf/hit_tracker/hit_tracker.js:169:10)
    at trackerOverview (chrome-extension://iglbakfobmoijpbigmlfklckogbefnlf/hit_tracker/hit_tracker.js:157:22)
    at initialize (chrome-extension://iglbakfobmoijpbigmlfklckogbefnlf/hit_tracker/hit_tracker.js:6:3)

* Version used: 2.4.0
* Browser Name and version: Chrome Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by Amelie121** [comment]
Nevermind. I just uninstalled and reinstalled and it's fine now lol
