### ISSUE TITLE
Missing Panda button from Hit finder

### ISSUE THREAD

**Issue by shaqsbit** [brandonhellman/mturk-suite#98]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

Hello,

I need to understand how to get back the panda button (which is missing) after a hit is tried to accept from Hit Finder.  All changed after the update and the recent update had set the thing right for just a little time for me.  I am unable to understand the issue at my end.

All the hits accepted/selected from Hit finder are not showing the Panda button.  It is working fine with Turkmaster though.  After you mentioned to check any error msg by pressing F12 and Console tab I did check and here is the error for your reference (started and ended the error msg with --- below)

---Uncaught (in promise) Error: Unable to find "reactComponents/alert/Alert".
    at ReactDOM.Promise (chrome-extension://iglbakfobmoijpbigmlfklckogbefnlf/js/react-dom-props.js:13:14)
    at new Promise (<anonymous>)
    at ReactDOM (chrome-extension://iglbakfobmoijpbigmlfklckogbefnlf/js/react-dom-props.js:3:10)
    at chrome.runtime.onMessage.addListener (chrome-extension://iglbakfobmoijpbigmlfklckogbefnlf/mturk/hit-catcher-buttons-missed.js:35:23)
    at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:138:26)
    at EventImpl.dispatch_ (extensions::event_bindings:387:35)
    at EventImpl.dispatch (extensions::event_bindings:409:17)
    at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:138:26)
    at messageListener (extensions::messaging:240:29)---

I am using the latest version of Chrome browser 66.0

Please advise further action for me.

**Comment by brandonhellman** [comment]
That is all I need, thanks. I'm 95% sure I know what the issue is, I'll work on a fix and get it out sometime tonight/tomorrow morning.
